using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;
using HarderNamespace.StaticName;

namespace HarderNamespace.StaticName.Test
{
    [TestFixture]
    public class ClassWithStaticMethTests
    {
        private ClassWithStaticMeth _ClassWithStaticMethUnderTest;
        [SetUp]
        public void SetUp()
        {
            _ClassWithStaticMethUnderTest = new ClassWithStaticMeth();
        }

        [Test]
        public void ClassMethTest()
        {
            int j = default;
            TestClass actual = _ClassWithStaticMethUnderTest.ClassMeth(j);
            TestClass expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetIntTest()
        {
            float g = default;
            string asd = default;
            int actual = ClassWithStaticMeth.GetInt(g, asd);
            int expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}