using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;
using HarderNamespace.InterfaceName;

namespace HarderNamespace.InterfaceName.Test
{
    [TestFixture]
    public class ClassWithInterTests
    {
        private ClassWithInter _ClassWithInterUnderTest;
        private Mock<ITestInt> _testIntDependency;
        [SetUp]
        public void SetUp()
        {
            int i = default;
            _testIntDependency = new Mock<ITestInt>();
            _ClassWithInterUnderTest = new ClassWithInter(i, _testIntDependency.Object);
        }

        [Test]
        public void VoidMethTest()
        {
            int k = default;
            float b = default;
            _ClassWithInterUnderTest.VoidMeth(k, b, _testDependency.Object);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void CharMethTest()
        {
            TestClass test = default;
            char actual = _ClassWithInterUnderTest.CharMeth(test);
            char expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}