using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;
using HarderNamespace.StaticName;

namespace HarderNamespace.StaticName.Test
{
    [TestFixture]
    public class StaticClassTests
    {
        [SetUp]
        public void SetUp()
        {
        }

        [Test]
        public void VoidMethTest()
        {
            bool Bool = default;
            int k = default;
            StaticClass.VoidMeth(Bool, k);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void BoolMethTest()
        {
            string s = default;
            bool actual = StaticClass.BoolMeth(s);
            bool expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}