using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;
using HarderNamespace.InterfaceName;

namespace HarderNamespace.InterfaceName.Test
{
    [TestFixture]
    public class ClassWithTwoInterTests
    {
        private ClassWithTwoInter _ClassWithTwoInterUnderTest;
        private Mock<ITestInt> _testIntDependency;
        private Mock<IMoreInt> _moreIntDependency;
        [SetUp]
        public void SetUp()
        {
            int i = default;
            _testIntDependency = new Mock<ITestInt>();
            _moreIntDependency = new Mock<IMoreInt>();
            _ClassWithTwoInterUnderTest = new ClassWithTwoInter(i, _testIntDependency.Object, _moreIntDependency.Object);
        }

        [Test]
        public void CharMethTest()
        {
            TestClass test = default;
            char actual = _ClassWithTwoInterUnderTest.CharMeth(test);
            char expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}