using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;
using HarderNamespace.InjectClass.ParanetClass;

namespace HarderNamespace.InjectClass.ParanetClass.Test
{
    [TestFixture]
    public class ChildClassTests
    {
        private ChildClass _ChildClassUnderTest;
        [SetUp]
        public void SetUp()
        {
            _ChildClassUnderTest = new ChildClass();
        }

        [Test]
        public void VoidMethTest()
        {
            _ChildClassUnderTest.VoidMeth();
            Assert.Fail("autogenerated");
        }

        [Test]
        public void CharMethTest()
        {
            char actual = _ChildClassUnderTest.CharMeth();
            char expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}