using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;
using SimpleNamespace;

namespace SimpleNamespace.Test
{
    [TestFixture]
    public class SimpleClassTests
    {
        private SimpleClass _SimpleClassUnderTest;
        [SetUp]
        public void SetUp()
        {
            _SimpleClassUnderTest = new SimpleClass();
        }

        [Test]
        public void VoidMethTest()
        {
            int k = default;
            float b = default;
            _SimpleClassUnderTest.VoidMeth(k, b);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void CharMethTest()
        {
            string s = default;
            char actual = _SimpleClassUnderTest.CharMeth(s);
            char expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}